modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/TheIllusiveC4/ConsecrationCompatibility/issues"
logoFile="${mod_icon}"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_url}"
authors="${mod_author}"
description='''
${mod_description}
'''
[[dependencies.consecrationcompat]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.consecrationcompat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2,1.16)"
    ordering="NONE"
    side="BOTH"
[[dependencies.consecrationcompat]]
    modId="consecration"
    mandatory=true
    versionRange="[FORGE-1.15.2-2.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.consecrationcompat]]
    modId="spartanweaponry"
    mandatory=false
    versionRange="[2.0.0 alpha 3,)"
    ordering="NONE"
    side="BOTH"
